vente:
    resource: "@VenteBundle/Resources/config/routing.yml"
    prefix:   /

depot:
    resource: '@DepotBundle/Controller/'
    type: annotation

employee:
    resource: '@EmployeBundle/Controller/'
    type: annotation

achat:
    resource: "@AchatBundle/Resources/config/routing.yml"
    prefix:   /

livraison:
    resource: "@LivraisonBundle/Resources/config/routing.yml"
    prefix:   /

vehicule:
    resource: "@VehiculeBundle/Resources/config/routing.yml"
    prefix:   /

service_apres_vente:
    resource: "@ServiceApresVenteBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"